#include "hss_driver.h"

/*
 * This file is a virtual STM32 HAL-style driver template.
 * Replace these external symbols with the real names generated by STM32CubeMX.
 */
extern SPI_HandleTypeDef hspi1;

#define HSS_SPI_HANDLE    hspi1
#define HSS_SPI_TIMEOUT   100u

static uint8_t hss_last_global_status = 0u;

static uint8_t hss_make_cmd(uint8_t op, uint8_t addr)
{
    return (uint8_t)(op | (addr & HSS_ADDR_MASK));
}

uint32_t hss_transfer24(uint8_t cmd, uint16_t data)
{
    uint8_t tx[3];
    uint8_t rx[3];

    tx[0] = cmd;
    tx[1] = (uint8_t)((data >> 8) & 0xFFu);
    tx[2] = (uint8_t)(data & 0xFFu);

    /*
     * Pseudo code for real STM32 project:
     *
     * HAL_GPIO_WritePin(HSS_CSN_GPIO_Port, HSS_CSN_Pin, GPIO_PIN_RESET);
     * HAL_SPI_TransmitReceive(&HSS_SPI_HANDLE, tx, rx, 3, HSS_SPI_TIMEOUT);
     * HAL_GPIO_WritePin(HSS_CSN_GPIO_Port, HSS_CSN_Pin, GPIO_PIN_SET);
     *
     * For now, this virtual demo returns 0 until connected to real hardware.
     */
    rx[0] = 0u;
    rx[1] = 0u;
    rx[2] = 0u;

    hss_last_global_status = rx[0];

    return ((uint32_t)rx[0] << 16) |
           ((uint32_t)rx[1] << 8) |
           ((uint32_t)rx[2]);
}

uint16_t hss_write_reg(uint8_t addr, uint16_t value)
{
    uint8_t cmd = hss_make_cmd(HSS_OP_WRITE, addr);
    uint32_t rx_frame = hss_transfer24(cmd, value);

    return (uint16_t)(rx_frame & 0xFFFFu);
}

uint16_t hss_read_reg(uint8_t addr)
{
    uint8_t cmd = hss_make_cmd(HSS_OP_READ, addr);
    uint32_t rx_frame = hss_transfer24(cmd, 0x0000u);

    return (uint16_t)(rx_frame & 0xFFFFu);
}

uint16_t hss_read_clear_status(uint8_t addr)
{
    uint8_t cmd = hss_make_cmd(HSS_OP_READ_CLEAR_STATUS, addr);
    uint32_t rx_frame = hss_transfer24(cmd, 0x0000u);

    return (uint16_t)(rx_frame & 0xFFFFu);
}

uint16_t hss_read_device_info(uint8_t addr)
{
    uint8_t cmd = hss_make_cmd(HSS_OP_READ_DEVICE_INFO, addr);
    uint32_t rx_frame = hss_transfer24(cmd, 0x0000u);

    return (uint16_t)(rx_frame & 0xFFFFu);
}

void hss_software_reset(void)
{
    (void)hss_transfer24(HSS_CMD_SW_RESET, 0x0000u);
}

void hss_clear_all_status(void)
{
    (void)hss_transfer24(HSS_CMD_CLEAR_ALL_STATUS, 0x0000u);
}

uint8_t hss_get_last_global_status(void)
{
    return hss_last_global_status;
}
